Update Migration doc
adobe/aepsdk-react-native pull request #251
Opened 2023-03-08 02:19 UTC by cacheung

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
Update Migration doc.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-08 23:43 UTC, yangyansong-adbe approved these changes

2023-03-09 00:22 UTC, praveek requested changes

2023-03-09 00:22 UTC, praveek commented on docs/migration.md
>      [AEPMobileCore lifecycleStart:@{@"contextDataKey": @"contextDataVal"}];
We need to check if the app is not in background before calling lifecycleStart.
Can you also update the other places with similar logic?

2023-03-09 17:14 UTC, rymorale commented on docs/migration.md
> +| @adobe/react-native-acpcampaign | @adobe/react-native-aepcampaignclassic |
the react-native-acpcampaign wrapper is for campaign standard. the aepcampaignclassic is brand new and does not have an existing acp version. the aepcampaignstandard wrapper is to be done.

2023-03-09 17:16 UTC, rymorale commented on packages/assurance/README.md
> +To connect to an Assurance session by scanning the QR code. Follow [Apple developer](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app) documentation to set cu
"To connect to an Assurance session by scanning the QR code, follow ..."

2023-03-09 17:18 UTC, rymorale commented on packages/assurance/README.md
> +To connect to an Assurance session by scanning the QR code. Follow the [Android documentation](https://developer.android.com/training/app-links/deep-linking) on information about how to setup a deepl
"To connect to an Assurance session by scanning the QR code, follow the [Android documentation](https://developer.android.com/training/app-links/deep-linking) for more information about how to setup a deeplink."

2023-03-09 17:41 UTC, praveek commented on docs/migration.md
> -| @adobe/react-native-acpcampaign | @adobe/react-native-aepcampaignclassic |
Can you add a line for campaignclassic?

2023-03-09 17:41 UTC, praveek approved these changes

2023-03-09 20:43 UTC, merged